### ISSUE TITLE
Vert.x 2.0 모듈로 올리기

### ISSUE THREAD

**Issue by keesun** [keesun/mod-socket-io#10]
험난하다 험난해.. 

https://groups.google.com/forum/#!topic/vertx/r7ri2GatkPs

**Comment by keesun** [comment]
걍 하지말까...

**Comment by m0er** [comment]
쓰레드 쭉 읽어보니 재미있네요 ㅋㅋ

**Comment by keesun** [comment]
읽지마 완전 삽질기야.ㅋㅋㅋ
