### ISSUE TITLE
Slightly misleading instructions

### ISSUE THREAD

**Issue by fjurcovici** [keesun/mod-socket-io#11]
The README says copy everything in dist to your vert.x lib dir to make socket.io available to verticles. If you do so, you also copy the v0.9 jar, which will be typically searched for classes before the 1.0 version, leading to an error when trying to run a verticle using socket.io. Removing that jar from dist is all that's required to fix this problem.

**Comment by keesun** [comment]
Oh, This is my mistake. Sorry.

Recently I didn't update that part of the README. I will update it soon. 

Thanks a lot!

**Comment by keesun** [comment]
I've update the `dist` directory. So, following the README has no problem now.
Thank you.
