### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by oxsav** [keesun/mod-socket-io#6]
In my project the core it's all of them in vertx. So try to not use node to run my socket.io server I want to use this module to have everything working with vertx.

In the examples that you put 
- /samples/tests/Issue5.js <- work well
- /samples/tests/Issue5.java <- not working well

If I run my application with "node Issue5.js" my clients connect well and switch the message weel in that channel but if I run the verticle with "vertx run Issue5.java" this is not connection well and in the most of times they not exchange the message to negotiate the sdp parameters. 

(Using this examples https://github.com/muaz-khan/WebRTC-Experiment/tree/master/socketio-over-nodejs/webrtc-signaling)

I don't know why, why code in Javascript (node) work and in Java (vertx) it's not working? 

My client file is in: https://gist.github.com/oxsav/5635084

If you can take a look should be great.

Thanks again

**Comment by oxsav** [comment]
Sorry again but one another thing. I try to follow the README that you have in mod-socket-io and add this :

``` javascript
repositories {
  maven { url 'http://dev.springsprout.org/nexus/content/groups/public/' }
  ...
}
```

and this:

``` javascript
dependencies {
  compile      "com.nhncorp:mod-socket-io:0.9.10"
  ...
}
```

But when I execute  "./mk build" returns me:

``` javascript
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve group:com.nhncorp, module:mod-socket-io, version:0.9.10.
   > Could not GET 'http://dev.springsprout.org/nexus/content/groups/public/com/nhncorp/mod-socket-io/0.9.10/mod-socket-io-0.9.10.pom'.
   > Could not GET 'https://oss.sonatype.org/content/repositories/snapshots/com/nhncorp/mod-socket-io/0.9.10/mod-socket-io-0.9.10.pom'.
   > Could not GET 'http://repo1.maven.org/maven2/com/nhncorp/mod-socket-io/0.9.10/mod-socket-io-0.9.10.pom'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2 mins 1.984 secs
```

**Comment by isyoon** [comment]
I guess, Springsprout's repository  server has gone away;

**Comment by keesun** [comment]
@oxsav 

I've seen your client codes but I don't know how It can work with my test codes. Have you ever tried my test server codes(issue5.js and issue5.java) with my test client code(issue5.html)?

https://github.com/keesun/mod-socket-io/blob/master/samples/web/tests/issue-5.html

When I tested issue5.java with above client codes it works fine. Can you try this one?

**Comment by oxsav** [comment]
Yes I tried your client code. And the other examples. But it seems to not work when it sends a lot of message. In your example we have a button to connect to io server and connect to a certain channel and then emit a message to that channel (namespace). In my example my client connects automatically  to a name space and starts to emit messages when it knows there are other clients connected to that namespace. All of this process is done automatically. Just have a button to start a conference and they start to switch messages. 

The problem is with the examples and running the server with "node Issue5.js" works, but when I try that with "vertx run Issue5.java" it doesn't work. So I have two clients connected to the server but when one of them start conference, most of the times, the other doesn't receive any message to negociate the session.

So your examples works fine, and the examples I gave you doesn't work with vert.x! (And I don't know why)

**Comment by keesun** [comment]
![2013-05-27 6 22 17 2](https://f.cloud.github.com/assets/463657/567251/1b192786-c6af-11e2-98ad-d5b6aa1a81b4.png)

I've updated the 'issue5 test" like above and I have checked it works fine with multiple clients. I will refer the left one as 'L' and the right one as 'R'
1. L is connected to the server.
2. L created the news channel.
3. L is connected to the news channel.
4. L had got an news channel's welcome message.
5. L said 'sdfsd'
6. R is connected to the news channel.
7. R had got an news channel's welcome message.
8. L also had got an news channel's welcome message.
9. R said 'sdfsdf' and got the message.
10. L also got the 'sdfsdf'
11. R said 'hello" and got the message.
12. L also got the "hello"

Is there anything wrong with this example or tests? You can also try this with sample/test/issue5.html.

**Comment by keesun** [comment]
@oxsav How have been to with this issue? I just wondering if you find it is working or not. Please let me know.
